# Generated by Django 6.0.2 on 2026-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('suburb', models.CharField(blank=True, max_length=255)),
                ('monthly_rent_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('self_employed', 'Self-employed'), ('student', 'Student'), ('retired', 'Retired')], max_length=20)),
                ('time_in_role', models.CharField(blank=True, max_length=50)),
                ('rental_history', models.CharField(blank=True, choices=[('rented_locally', 'Rented locally'), ('rented_overseas', 'Rented overseas'), ('first_time_renter', 'First-time renter'), ('owned_home', 'Owned previous home')], max_length=20)),
                ('household_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('household_income_period', models.CharField(blank=True, choices=[('annual', 'Annually'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('individual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('individual_income_period', models.CharField(blank=True, choices=[('annual', 'Annually'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('proof_of_income', models.CharField(blank=True, choices=[('recent_payslip', 'Recent payslip'), ('bank_statements', 'Bank statements only'), ('none', 'None')], max_length=20)),
                ('moving_with_adults', models.PositiveIntegerField(blank=True, null=True)),
                ('moving_with_children', models.PositiveIntegerField(blank=True, null=True)),
                ('moving_with_pets', models.PositiveIntegerField(blank=True, null=True)),
                ('context_issues', models.TextField(blank=True)),
                ('readiness_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
