# Generated by Django 6.0.2 on 2026-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='gap_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
