# Generated by Django 6.0.2 on 2026-02-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_plan', '0002_initial'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cover_letters', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ap_cover_letter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenceletter',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_reference_letters', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='referenceletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_reference_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_documents', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='completedtask',
            constraint=models.UniqueConstraint(fields=('user', 'assessment', 'task_key'), name='unique_user_assessment_task'),
        ),
    ]
