# Generated by Django 6.0.2 on 2026-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
