# Generated by Django 6.0.2 on 2026-02-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0003_initial'),
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cover_letters', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='referenceletter',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_reference_letters', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_documents', to='assessments.assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='completedtask',
            unique_together={('assessment', 'task_key')},
        ),
    ]
