# Generated by Django 6.0.2 on 2026-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0004_coverletter_assessment_referenceletter_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='content',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='action_plan/cover_letters/'),
        ),
    ]
