# Generated by Django 6.0.2 on 2026-02-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0005_remove_coverletter_content_coverletter_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceletter',
            name='text_content',
        ),
    ]
