# Generated by Django 6.0.2 on 2026-02-23 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0006_remove_referenceletter_text_content'),
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedtask',
            unique_together={('user', 'assessment', 'task_key')},
        ),
    ]
