# Generated by Django 6.0.2 on 2026-02-23 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0007_alter_completedtask_unique_together'),
        ('assessments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedtask',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='completedtask',
            constraint=models.UniqueConstraint(fields=('user', 'assessment', 'task_key'), name='unique_user_assessment_task'),
        ),
    ]
