# Generated by Django 6.0.2 on 2026-02-26 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('confident', 'Confident'), ('direct', 'Short & Direct')], default='professional', max_length=50)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('student', 'Student'), ('retired', 'Retired')], max_length=20, null=True)),
                ('rental_history_type', models.CharField(blank=True, choices=[('first_time', 'First Time Renter'), ('rented_before', 'Rented Before'), ('rented_overseas', 'Rented Overseas')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('base_inputs', models.JSONField(default=dict)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('is_premium_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
