# Generated by Django 6.0.2 on 2026-02-22 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('confident', 'Confident'), ('direct', 'Short & Direct')], default='professional', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('base_inputs', models.JSONField(default=dict)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('is_premium_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cover_letters.coverletter')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cover_letter', 'version_number')},
            },
        ),
    ]
