# Generated by Django 6.0.2 on 2026-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('student', 'Student'), ('retired', 'Retired')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='rental_history_type',
            field=models.CharField(blank=True, choices=[('first_time', 'First Time Renter'), ('rented_before', 'Rented Before'), ('rented_overseas', 'Rented Overseas')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CoverLetterVersion',
        ),
    ]
