# Generated by Django 6.0.2 on 2026-03-09 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tenant_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assessments.assessment')),
            ],
        ),
    ]
