# Generated by Django 6.0.2 on 2026-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/tenant_reports/'),
        ),
    ]
